### ISSUE TITLE
error on useing coverage

### ISSUE THREAD

**Issue by sb185296** [bibipkins/dotnet-test-reporter#13]
hi ,

when i using this action only on TRX its working

```
dotnet test "tests/tests.csproj" --collect:"XPlat Code Coverage" --results-directory:"coverage"
```

but when i use it on coverage i get the below error
also i was must use like that : bibipkins/dotnet-test-reporter@v1.0.0-beta.4
and not like its was in the docs

    - name: Unit Test Results
      uses: bibipkins/dotnet-test-reporter@v1.0.0-beta.4
      with:
        test-results: ./apitest/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-coverage: ./coverage/coverage.cobertura.xml
        comment-title: 'Unit Test Results'

![image](https://user-images.githubusercontent.com/66299621/178579968-fd868db9-8150-4d50-b868-3b7c1cc98406.png)

my file is : coverage.cobertura.xml
```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0.0613" branch-rate="0.049400000000000006" version="1.9" timestamp="1657653025" lines-covered="2207" lines-valid="35996" branches-covered="725" branches-valid="14652">
  <sources>
    <source></source>
  </sources>
  <packages>
```

**Comment by bibipkins** [comment]
Hi @sb185296! I believe you receive the error because your coverage is in `cobertura` format and this action can work only with `opencover` for now. This is also specified in the description to this action [on its market page](https://github.com/marketplace/actions/dotnet-test-reporter). I will try to add more formats when I have some free time. But it should be easy to generate `opencover` format unless you require `cobertura` specifically for some other CI tool
Also can you please explain what's exactly the difference between the docs and how you use this action? Thanks

**Comment by bibipkins** [comment]
@sb185296  oh nevermind, I see the difference. I was copying github's template, I will fix the description, thank you!

**Comment by sb185296** [comment]
hi
thanks for for that !!
hmm can you update me when its ready i will do a test :)

thanks

**Comment by sb185296** [comment]
update 
in the SLN i add

 <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="1.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
  </ItemGroup>


and then i run 
dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover

and now i use the opencover same error :\

![image](https://user-images.githubusercontent.com/66299621/178679051-fff1ea00-a753-4ce9-a166-09f064ce6d8f.png)
 


![image](https://user-images.githubusercontent.com/66299621/178679035-0e8a9851-4667-4d37-8732-fc11d4fd689c.png)

**Comment by bibipkins** [comment]
@sb185296 I can share a command that works for me. I ran the tests as a part of a docker build so my command is formatted for Linux so don't mind that as well as my file paths.
```
dotnet test "path to my test project" \
    --configuration Release \
    --logger "trx;LogFileName=../../../../test-results/unit-tests.trx" \
    -p:CollectCoverage=true \
    -p:CoverletOutputFormat="opencover" \
    -p:CoverletOutput=/test-results/cover.xml
```
In test project I have this setup (project is on dotnet core 3.1 but it should not matter much)
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="3.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="Moq" Version="4.17.2" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    REFERENCES TO PROJECTS UNDER TEST
  </ItemGroup>

</Project>
```

**Comment by sb185296** [comment]
ya i know that its workin but somting was change in V5.0 and 6.0
and its not working any more...i still get same error

any chance that you can add flag of cobertura ? or support it ?
