### ISSUE TITLE
Feature: Node.JS Glob pattern

### ISSUE THREAD

**Issue by actuarysailor** [bibipkins/dotnet-test-reporter#28]
Can we make this search for the coverage and test result files with a glob pattern?  This looks to be the most promising of the sorbet test reporters out there, but is limited by the use of non-dynamic file paths.

**Comment by bibipkins** [comment]
Hello @actuarysailor! Thank you for checking out this GitHub action!
Yes, I think it should be possible. I can try to implement it over the weekend unless you already have some code/implementation in mind you would like to share

**Comment by bibipkins** [comment]
@actuarysailor you can try out v1.3.0 it should allow using glob for both test results and coverage. Test results path still accepts multiple files, coverage expects a single file
