### ISSUE TITLE
Large code base with hundreds of tests - summary missing

### ISSUE THREAD

**Issue by shawner18** [bibipkins/dotnet-test-reporter#30]
We have a large project that exceeds the markdown post for the test summary information. The information below is reported. It would be nice if this could be split or perhaps posted to a file, that could be added to the pr.

`$GITHUB_STEP_SUMMARY upload aborted, supports content up to a size of 1024k, got 54351k. For more information see: https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions#adding-a-markdown-summary`

**Comment by bibipkins** [comment]
Hi @shawner18! thanks for checking out this action!
Thank you for the provided suggestions and the PR! I think both ideas make sense. I will review it as soon as I have some time.
A couple of quick temporary solutions that might help in the meantime:
- you can use `--verbosity=minimal` with your `dotnet test` command to reduce the amount of output
- in case you are using Entity Framework - disable EF logging during the test run, it can grow huge
- split tests into multiple runs (could be based on project/test-type/team) and have the action run separately for each
