### ISSUE TITLE
It throws error when there is no test 

### ISSUE THREAD

**Issue by maxisam** [bibipkins/dotnet-test-reporter#33]
currently it expects there is at least one test in the report, if there is no test in the report, it will throw errors.

Thanks for the great tool !

**Comment by maxisam** [comment]
https://github.com/bibipkins/dotnet-test-reporter/blob/311db8b035a1df3874396e9dc831d4c54903eb81/src/parsers/trx.ts#L44

I believe it is from this line.

So if there is no test, it doesn't have <Results> tag

**Comment by bibipkins** [comment]
@maxisam, thank you for checking out the action and reporting the bug! I will try to fix it asap. Also thanks for digging into the issue ❤️ !

**Comment by maxisam** [comment]
no problem. I created a PR to fix this, since this is more like a edge case for my project.

**Comment by bibipkins** [comment]
@maxisam  Thank you for your contribution! I merged your PR and created a new release **v1.3.1** you can try out now. Feel free to reopen the if the problem persists
