### ISSUE TITLE
doesn't update comment as expected

### ISSUE THREAD

**Issue by maxisam** [bibipkins/dotnet-test-reporter#35]
basically post-new-comment: false doesn't work. I think it is because of my case (again). 

https://github.com/maxisam/dotnet-test-reporter/blob/13ca76c96a6cd31e751b7b58477cdd58b1118dbf/src/utils/comments.ts#L62

If I use a token that is not a default token, it won't be a bot

**Comment by bibipkins** [comment]
Can you please provide more details? A screenshot of a comment/comments you get from the action could help. Also would be helpful to see your GitHub yaml file.

**Comment by bibipkins** [comment]
I added a "bot check" back when I made the tool to avoid the case when someone posts a comment with a header that could be recognized as a test-reporter comment since the comment header can be customized by a user

**Comment by maxisam** [comment]
basically it is a token from an account, so it isn't identified as a bot

so this line won't be true, and it can't find the comment to update.

`const isBotUserType = comment.user?.type === 'Bot' `

I don't know what is the best way to solve this, might be need to query the name of the token first and check it

**Comment by maxisam** [comment]
I think something like this might work

```
const username = await octokit.rest.users.getAuthenticated();
const isBotUserType = comment.user.login ===  username.data.login ;
```

i am going to test this

**Comment by maxisam** [comment]
Well, it doesn't work with the default token. await octokit.rest.users.getAuthenticated(); requires token with user scope permission

**Comment by bibipkins** [comment]
@maxisam Sorry for taking so long to respond! I reviewed and merged your PR. I created a new release **v1.3.2**, I would appreciate if you could try it out and confirm if the issue is fixed

**Comment by maxisam** [comment]
It is fixed. I have been using the same code already. Thanks for quick response. I don't think I respond to my own OSS project as fast as you do. lol
