### ISSUE TITLE
show sha as first 7 characters instead of 8

### ISSUE THREAD

**Issue by maxisam** [bibipkins/dotnet-test-reporter#38]
because github commit sha only shows 7 characters

<img width="120" alt="image" src="https://github.com/bibipkins/dotnet-test-reporter/assets/456807/b4a09316-c9a8-4fab-9c5b-db9aa472fb96">

I think if it only shows 7 characters, it is easier to eye ball the commit quickly.

if you are fine with it, I can push a PR for it.

**Comment by bibipkins** [comment]
You are right, thank you for pointing it out! Fixed in #40. Please try out new version **v1.3.3**

**Comment by maxisam** [comment]
Thanks!
